export const data = [
    {
        id: 1,
        brand: "Santa Cruz",
        nombre: "Dollar Flame",
        categoryId: 1,
        category: "deck",
        descripcion:"Santa Cruz Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 17999,
        stock: 2,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947936/skates/SKATESANTACRUZ1_nlvsed.png"
    },
    {
        id: 2,
        brand: "Santa Cruz",
        nombre: "Crane Dot",
        categoryId: 1,
        category: "deck",
        descripcion:"Santa Cruz Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 24999,
        stock: 6,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947928/skates/SKATESANTACRUZ2_srzh7z.png"
    },
    {
        id: 3,
        brand: "Santa Cruz",
        nombre: "Freak",
        categoryId: 1,
        category: "deck",
        descripcion:"Santa Cruz Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 24999,
        stock: 4,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947930/skates/SKATESANTACRUZ3_f4ntwz.png"
    },
    {
        id: 4,
        brand: "Santa Cruz",
        nombre: "Lucky Cat",
        categoryId: 1,
        category: "deck",
        descripcion:"Santa Cruz Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 17999,
        stock: 9,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947931/skates/SKATESANTACRUZ4_mpwlwq.png"
    },
    {
        id: 5,
        brand: "Santa Cruz",
        nombre: "Wooten",
        categoryId: 1,
        category: "deck",
        descripcion:"Santa Cruz Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 17999,
        stock: 3,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947927/skates/SKATESANTACRUZ5_qlopaz.png"
    },
    {
        id: 6,
        brand: "Creature",
        nombre: "Erosion",
        categoryId: 1,
        category: "deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 24999,
        stock: 15,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947932/skates/SKATECREATURE1_vuuvwo.png"
    },
    {
        id: 7,
        brand: "Creature",
        nombre: "Russell Skull",
        categoryId: 1,
        category: "deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 17999,
        stock: 7,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947936/skates/SKATECREATURE2_x2dqos.png"
    },
    {
        id: 8,
        brand: "Creature",
        nombre: "Russell",
        categoryId: 1,
        category: "deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 17999,
        stock: 5,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947931/skates/SKATECREATURE3_ytazbr.png"
    },
    {
        id: 9,
        brand: "Creature",
        nombre: "Martinez",
        categoryId: 1,
        category: "deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 17999,
        stock: 6,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947935/skates/SKATECREATURE4_v1a8kt.png"
    },
    {
        id: 10,
        brand: "Creature",
        nombre: "Deathcard",
        categoryId: 1,
        category: "deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 24999,
        stock: 6,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947930/skates/SKATECREATURE5_z546nz.png"
    },
    {
        id: 11,
        brand: "Santa Cruz",
        nombre: "Flier Hand",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Santa Cruz Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 3,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947934/skates/COMPLETESANTACRUZ1_vlrmy4.png"
    },
    {
        id: 12,
        brand: "Santa Cruz",
        nombre: "Screaming",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Santa Cruz Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 4,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947931/skates/COMPLETESANTACRUZ2_a3p1db.png"
    },
    {
        id: 13,
        brand: "Santa Cruz",
        nombre: "Classic Dot",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Santa Cruz Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 3,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947929/skates/COMPLETESANTACRUZ3_v4mhlg.png"
    },
    {
        id: 14,
        brand: "Santa Cruz",
        nombre: "Dot",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Santa Cruz Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 5,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947928/skates/COMPLETESANTACRUZ4_dyz8nd.png"
    },
    {
        id: 15,
        brand: "Santa Cruz",
        nombre: "Flier Dot",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Santa Cruz Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 8,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947925/skates/COMPLETESANTACRUZ5_vhvqnm.png"
    },
    {
        id: 16,
        brand: "Creature",
        nombre: "Prowler",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Creature Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 7,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947937/skates/COMPLETECREATURE1_yr2jxe.png"
    },
    {
        id: 17,
        brand: "Creature",
        nombre: "Deathcard",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Creature Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 5,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947933/skates/COMPLETECREATURE2_dl2eoa.png"
    },
    {
        id: 18,
        brand: "Creature",
        nombre: "Metallic Logo",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Creature Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 6,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947927/skates/COMPLETECREATURE3_a82vdm.png"
    },
    {
        id: 19,
        brand: "Creature",
        nombre: "Mummy Logo",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Creature Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 3,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947935/skates/COMPLETECREATURE4_imoxft.png"
    },
    { 
        id: 20,
        brand: "Creature",
        nombre: "Large Logo",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Creature Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 34999,
        stock: 10,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947935/skates/COMPLETECREATURE5_adrpqh.png"
    },
    {
        id: 21,
        brand: "Creature",
        nombre: "Lock Wood",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 17999,
        stock: 9,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947929/skates/novedad_1_p9jmh3.png"
    },
    {
        id: 22,
        brand: "Creature",
        nombre: "John Gardner",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 24999,
        stock: 2,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947930/skates/novedad_2_d2bezq.png"
    },
    {
        id: 23,
        brand: "Creature",
        nombre: "Kimbel Guitar",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 24999,
        stock: 8,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947929/skates/novedad_3_nbra5o.png"
    },
    {
        id: 24,
        brand: "Creature",
        nombre: "Martinez Hell",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 17999,
        stock: 6,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947935/skates/novedad_4_omfhfw.png"
    },
    {
        id: 25,
        brand: "Creature",
        nombre: "Baekel",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 4,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947933/skates/novedad_5_t1j0nb.png"
    },
    {
        id: 26,
        brand: "Creature",
        nombre: "Willis Kimbel",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 15,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947936/skates/novedad_6_fmssby.png"
    },
    {
        id: 27,
        brand: "Creature",
        nombre: "Provost BW",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 5,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947926/skates/novedad_7_g5wijs.png"
    },
    {
        id: 28,
        brand: "Creature",
        nombre: "Provost",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 35,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947927/skates/novedad_8_h2weiy.png"
    },
    {
        id: 29,
        brand: "Creature",
        nombre: "Mushroom",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 25,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947931/skates/novedad_9_sbq18v.png"
    },
    {
        id: 30,
        brand: "Creature",
        nombre: "Violet Brain",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 22,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947933/skates/novedad_10_kbtuz9.png"
    },
    {
        id: 31,
        brand: "Creature",
        nombre: "Green Creep",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 13,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947926/skates/novedad_11_bmudaw.png"
    },
    {
        id: 32,
        brand: "Creature",
        nombre: "Blue Creep",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 18,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947926/skates/novedad_12_gcvt3r.png"
    },
    {
        id: 33,
        brand: "Creature",
        nombre: "Soft",
        categoryId: 2,
        category: "Skate Complete",
        descripcion:"Creature Complete, Skateboard pre armado con los mejores productos de la marca, Hecha de 7 capas de maple canadiense",
        precio: 26000,
        stock: 16,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947932/skates/novedad_13_iclxrq.png"
    },
    {
        id: 34,
        brand: "Creature",
        nombre: "Brekkel",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 17,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947932/skates/novedad_14_qr2wuy.png"
    },
    {
        id: 35,
        brand: "Santa Cruz",
        nombre: "Creature S Cruz ",
        categoryId: 1,
        category: "Deck",
        descripcion:"Creature Deck, Fabricada con 7 capas de maple canadiense prensado individualmente para una mayor resistencia de la misma",
        precio: 19000,
        stock: 12,
        image: "https://res.cloudinary.com/lechon/image/upload/v1661947937/skates/novedad_15_dp2lng.png"
    },
    {
        id: 36,
        brand: "Santa Cruz",
        nombre: "Street Creep",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Street Creep Shaped Cruzer con gráfico brillante sobre tabla de arce norteamericano de 7 capas con ejes Krux 9.0 y ruedas OJ Keyframe de 58 mm y 87a.",
        precio: 26000,
        stock: 12,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210013/skates/LongSCBWSkull_btusir.png"
    },
    {
        id: 37,
        brand: "Santa Cruz",
        nombre: "Things Roskopp Face",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards X Stranger Things Rob Roskopp Face cruzer completo presenta la forma OG con ejes Krux 9.0 K5 y ruedas Slime Balls OG Slime de 60 mm en 78a.",
        precio: 27000,
        stock: 12,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210013/skates/LongSCGreenBlueStranger_mc1g82.png"
    },
    {
        id: 38,
        brand: "Santa Cruz",
        nombre: "Things Meek Slasher",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards X Stranger Things Keith Meek Slasher cruzer completo presenta la forma OG con ejes Krux 9.0 K5 y ruedas Slime Balls OG Slime de 60 mm en 78a.",
        precio: 26000,
        stock: 12,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210012/skates/LongSCBlueRedStranger_cp6xor.png"
    },
    {
        id: 39,
        brand: "Santa Cruz",
        nombre: "Hand Pintail Cruiser",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Screaming Hand Pintail Longboard Cruzer con forma de pintail más pequeña en una plataforma de 9 capas con ejes Kingpin invertidos Bullet de 160 mm y ruedas Slime Balls de 60 mm 78a de la marca Santa Cruz.",
        precio: 25000,
        stock: 12,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210013/skates/LongSCBlueDarkBackLogo_mpiydv.png"
    },
    {
        id: 40,
        brand: "Santa Cruz",
        nombre: "Dot Pintail Cruiser",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Stipple Wave Pintail Longboard Cruzer con forma de pintail más pequeña en una plataforma de 9 capas con ejes de pivote inverso Bullet de 160 mm y ruedas Slime Balls de 60 mm 78a de la marca Santa Cruz.",
        precio: 25000,
        stock: 12,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210012/skates/LongSCFishRib_ya7anj.png"
    },
    {
        id: 41,
        brand: "Santa Cruz",
        nombre: "Roskopp Drop Down",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Decoder Roskopp Dropdown Longboard Cruzer con un gráfico brillante de punto de decodificador transformador en una forma desplegable de tamaño mediano actualizada y moderna con huecos de rueda enrutados, nuevos ejes de descenso con pivote inverso Bullet de 160 mm y ruedas Slimeballs de la marca Santa Cruz de 66 mm y 78a. La impresión de la cubierta cambia cuando se ve a través de la etiqueta colgante de la lente del decodificador incluida.",
        precio: 26000,
        stock: 22,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210012/skates/LongSCHypnosis_zwfokg.png"
    },
    {
        id: 42,
        brand: "Santa Cruz",
        nombre: "Distress Cruiser",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Contra Distress Cruzer en una tabla de arce norteamericano de 7 capas con estilo de finales de los 80 con ejes Krux 9.0 y ruedas OJ Keyframe de 58 mm 87a.",
        precio: 25000,
        stock: 8,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210011/skates/LongSCBluePsycho_ohrja6.png"
    },
    {
        id: 43,
        brand: "Santa Cruz",
        nombre: "Drop Thru Cruiser",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Classic Dot Drop Thru Longboard Cruzer que presenta una plataforma de 9 capas con forma de caída de tamaño mediano con ejes de descenso con pivote inverso Bullet de 180 mm y ruedas Slime Balls de la marca Santa Cruz de 66 mm y 78a.",
        precio: 27000,
        stock: 7,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210010/skates/LongSCBlackClassic_slczxz.png"
    },
    {
        id: 44,
        brand: "Santa Cruz",
        nombre: "Split Hand Cruiser",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Split Hand Dropdown Longboard Cruzer con una forma desplegable de tamaño mediano actualizada y moderna con huecos de rueda enrutados, nuevos ejes de descenso con pivote inverso Bullet de 160 mm y ruedas Slime Balls de la marca Santa Cruz de 66 mm.",
        precio: 27000,
        stock: 6,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210010/skates/LongSC3DSquare_k4x2rq.png"
    },
    {
        id: 45,
        brand: "Santa Cruz",
        nombre: "Crane Dot Shark",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Crane Dot Shark Cruzer con arte de Mako @makoyamaki, basado en el arte original de Jim Phillips, en forma inspirada en una tabla de surf de 7 capas con camiones Bullet de 140 mm, elevadores en ángulo y ruedas de 65 mm 78a.",
        precio: 25500,
        stock: 11,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210010/skates/LongSCRisingStork_n1tecr.png"
    },
    {
        id: 46,
        brand: "Santa Cruz",
        nombre: "Glow Dot Shark",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards, en colaboración con Carver, presenta una línea completamente nueva de surf skate cruzers con tablas de arce norteamericano de 7 capas de alta calidad, ruedas con la marca OJ o Slime Balls y camiones Carver surfskate, todos diseñados y ajustados a medida por Santa Cruz.Santa Cruz Glow Dot Shark Surf Skate Cruzer con una forma de tiburón personalizada en arce norteamericano de 7 capas con distancia entre ejes de 16, juego de ejes Carver CX y ruedas Slime Balls OG Slime Light Ups de 66 mm y 78a.Los Slimeballs Light Ups cuentan con luces LED que se encienden cuando rueda, impulsadas por la rotación de la rueda y el rodamiento. No requiere pilas, viene con rodamientos. La forma OG Slime es una rueda de crucero con rodamiento central simétrico y versátil con uretano 78a suave.",
        precio: 28000,
        stock: 5,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210009/skates/LongSCNeonLogo_cr6iis.png"
    },
    {
        id: 47,
        brand: "Santa Cruz",
        nombre: "Rad Dot Pintail",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Forma de pintail más pequeña y actualizada en una plataforma de 9 capas con camiones Bullet RKP de 180 mm y ruedas Slimeballs OG Slime de 60 mm",
        precio: 23000,
        stock: 7,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210010/skates/longboardSCcuadric_kgyb0l.png"
    },
    {
        id: 48,
        brand: "Santa Cruz",
        nombre: "Roskopp Five Drop",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Rob Roskopp Five Drop Thru Longboard Cruzer con una plataforma de 9 capas con forma de caída de tamaño mediano con ejes de descenso Bullet de 180 mm con pivote inverso y ruedas Slime Balls de la marca Santa Cruz de 66 mm y 78a.",
        precio: 26000,
        stock: 23,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210009/skates/LongSCPsychoMonsters_klvwnk.png"
    },
    {
        id: 49,
        brand: "Santa Cruz",
        nombre: "Wave Dot Splice ",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Wave Dot Splice Drop Thru Longboard Cruzer que presenta una plataforma de 9 capas con forma de caída de tamaño mediano con ejes de descenso Bullet de 180 mm con pivote inverso y ruedas Slimeballs de la marca Santa Cruz de 66 mm y 78a.",
        precio: 24000,
        stock: 8,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210009/skates/LongSCWave_w2zmkv.png"
    },
    {
        id: 50,
        brand: "Santa Cruz",
        nombre: "Serape Dot Pintail",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards Serape Dot Pintail Longboard Cruzer presenta una forma de pintail más pequeña y actualizada en una plataforma de 9 capas con ejes Bullet de 160 mm con pivote inverso y ruedas Santa Cruz de 60 mm 78a Slimeballs.",
        precio: 26000,
        stock: 8,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210008/skates/LongSCRasta_qf0l2f.png"
    },
    {
        id: 51,
        brand: "Santa Cruz",
        nombre: "Wave Dot Splice Pintail",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Forma de pintail más pequeña y actualizada en una plataforma de 9 capas con camiones Bullet RKP de 180 mm y ruedas Slime Balls de la marca Santa Cruz de 60 mm",
        precio: 25000,
        stock: 8,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210008/skates/LongSCParalel_q0vrhm.png"
    },
    {
        id: 52,
        brand: "Santa Cruz",
        nombre: "Iridescent Dot Shark",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Forma inspirada en una tabla de surf de 7 capas con camiones Bullet de 140 mm, bandas en ángulo y ruedas 78a de 65 mm",
        precio: 26000,
        stock: 10,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210008/skates/LongSCMetalGlowLogo_jn1riq.png"
    },
    {
        id: 53,
        brand: "Santa Cruz",
        nombre: "Flame Dot Shark",
        categoryId: 3,
        category: "Cruiser / Longboard",
        descripcion:"Santa Cruz Skateboards, en colaboración con Carver, presenta una línea completamente nueva de surf skate cruzers con tablas de arce norteamericano de 7 capas de alta calidad, ruedas con la marca OJ o Slime Balls y camiones Carver surfskate, todos diseñados y ajustados a medida por Santa Cruz. Santa Cruz Flame Dot Shark Surf Skate Cruzer con forma de tiburón personalizada en arce norteamericano de 7 capas con distancia entre ejes de 16, juego de ejes Carver CX y ruedas OJ Hot Juice de 60 mm y 78a.",
        precio: 25000,
        stock: 6,
        image: "https://res.cloudinary.com/lechon/image/upload/v1662210008/skates/LongSCLavaCarver_glwk4v.png"
    }
  ]